App:
  port: 3000

database_erp:
  dbhost: 100.113.201.122
  dbport: 3306
  username: root
  password: Mark3113
  dbname: attendance

jwt:
  access_token: thisisasupersecretkey123
  refresh_token: thisisarefreshsecretkey12
