App:
  port: 4000

database_erp:
  dbhost: localhost
  dbport: 3306
  username: root
  password: 
  dbname: timemint

jwt:
  access_token: thisisasupersecretkey123
  refresh_token: thisisarefreshsecretkey12
